name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.12.0
      with:
        dotnet-version: 7.0.x

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Restore Dependencies
      run: dotnet restore Dilan.ServiceDiscovery.sln

    - name: Build
      run: dotnet build Dilan.ServiceDiscovery.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Test\\BlazorServerAppTests\\BlazorServerAppTests.csproj --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
